### ISSUE TITLE
Here be dragons

### ISSUE THREAD

**Issue by ekinhbayar** [ekinhbayar/slack-driver#1]
#### To-Do
- [ ] Implement [app_rate_limited](https://api.slack.com/events/app_rate_limited)
- [ ] Implement [channel_created](https://api.slack.com/events/channel_created)
- [ ] Implement [message.im](https://api.slack.com/events/message.im)
